# .github/workflows/send_reminders.yml
name: "Send Booking Reminders"

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  send_reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call the send-reminders API endpoint
        run: |
          curl --request GET \
          --url '${{ secrets.BASE_URL }}/api/cron/send-reminders' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
