# .github/workflows/send_reminders.yml

name: "Send Booking Reminders"

# Disparador: se ejecuta en un horario programado
on:
  schedule:
    # Ejecutar CADA MINUTO (ajusta si prefieres otra frecuencia, ej: '*/5 * * * *' para cada 5 mins)
    - cron: "*/5 * * * *"
  # También puedes añadir un disparador manual para probarlo
  workflow_dispatch:

jobs:
  send_reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call the send-reminders API endpoint
        run: |
          curl --request GET \
          --url '${{ secrets.BASE_URL }}/api/cron/send-reminders' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
